### ISSUE TITLE
Cost for running this in Azure?

### ISSUE THREAD

**Issue by major** [schnerring/infrastructure-core#12]
Thanks for sharing your terraform setup with kubernetes! I found it while searching for some methods of deploying a Matrix container.

Do you have a rough estimate of how much it costs to run this infrastructure in Azure each month?

**Comment by schnerring** [comment]
Sure! Currently it's around CHF 80 per month

| Monthly cost `CHF` | Service                           |
| ------------------ | --------------------------------- |
| 32                 | `Standard_B2ms` VM reservations   |
| 19                 | Node OS disk                      |
| 17                 | Load Balancer with `Standard` SKU |
| 7                  | two public IPs                    |
| 5                  | k8s PVC storage                   |

For a while, I wanted to optimize the cost for this but just didn't get around to it, yet. [I wrote about reducing storage cost on my blog](https://schnerring.net/blog/reduce-storage-costs-when-deploying-azure-kubernetes-service-clusters-with-terraform/].

The CHF 19 for the node OS disk are wasted, really. Ephemeral OS disks are much preferred, but B-Series instances don't support it. Why AKS even supports those types of VMs then is beyond me.

Also, I probably could get away with a `Basic` SKU load balancer since I only run a single node cluster.

So I basically could run it for around CHF 55 in the `Switzerland North` region.

**Comment by major** [comment]
@schnerring Wow, thanks for taking the time to share all of that. I'm going to add your blog to my RSS feed reader. 😉
